import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(root, "public");
const outFile = path.join(root, "src/data/publicRoutes.ts");

function listPublicFiles(dir, base = "") {
  if (!fs.existsSync(dir)) {
    return [];
  }

  const files = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) {
      continue;
    }

    const relativePath = base ? `${base}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      files.push(...listPublicFiles(path.join(dir, entry.name), relativePath));
    } else {
      files.push(relativePath);
    }
  }

  return files.sort();
}

export function writePublicRoutes() {
  const publicRoutes = listPublicFiles(publicDir);
  const content = `// Auto-generated by scripts/generatePublicRoutes.mjs — do not edit.
export const publicRoutes = ${JSON.stringify(publicRoutes)} as const;
`;
  fs.writeFileSync(outFile, content);
}

if (import.meta.url === new URL(process.argv[1], "file:").href) {
  writePublicRoutes();
}
