// Auto-generated by scripts/generatePublicRoutes.mjs — do not edit.
export const publicRoutes = ["BingSiteAuth.xml","favicon.ico","favicon.png","google0f87563984e489d5.html","images/brown-book-192x192.png","images/brown-book-512x512.png","robots.txt","sitemap.txt"] as const;
